[package]
name = "witnet_rad_engine"
version = "0.1.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
description = "rad engine component"
edition = "2018"

[dependencies]
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.28"
reqwest = "0.9.2"
